# -*- coding: utf-8 -*-
{
    "name": "SCE Connector MercadoLibre",
    "version": "19.0.1.2.0",
    "summary": "Conector MercadoLibre para SCE",
    "category": "Sales",
    "author": "Softwork",
    "website": "https://swsistemas.com",
    "license": "LGPL-3",
    "depends": [
        "softwork_ecommerce_conector_base",
    ],
    "pre_init_hook": "pre_init_deduplicate_ml_question_channels",
    "data": [
        "security/ir.model.access.csv",
        "security/sce_client_premium_rules.xml",
        "data/ir_cron.xml",
        "data/marketplace_ir_cron.xml",
        "views/ml_category_search_wizard_views.xml",
        "views/ml_attribute_option_picker_wizard_views.xml",
        "views/marketplace_publication_core_views.xml",
        "views/marketplace_publication_views.xml",
        "views/marketplace_account_views.xml",
        "views/marketplace_product_mapping_views.xml",
        "views/marketplace_sale_order_views.xml",
        "views/sce_job_marketplace_views.xml",
        "views/marketplace_product_status_wizard_views.xml",
        "views/marketplace_product_template_views.xml",
        "views/ml_test_user_wizard_views.xml",
        "views/ml_attribute_editor_wizard_views.xml",
        "views/ml_publish_config_wizard_views.xml",
        "views/ml_publish_assistant_wizard_views.xml",
        "views/remote_publication_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
}