# -*- coding: utf-8 -*-
"""
Softwork Commerce Engine (SCE)

Notification Service

Central notification manager for SCE.

Responsible for:

- Email notifications
- Template rendering
- Recipient resolution
- Notification dispatch

Future versions:

- WhatsApp
- Telegram
- Slack
- Microsoft Teams
- Discord
"""

from __future__ import annotations

import logging

from odoo import api, models

_logger = logging.getLogger(__name__)


class SCENotificationService(models.AbstractModel):
    """
    Central notification service.

    Every notification generated by SCE
    should pass through this service.
    """

    _name = "sce.notification.service"

    _description = "SCE Notification Service"

    # =========================================================
    # Template Resolution
    # =========================================================

    @api.model
    def get_template(self, xmlid):
        """
        Returns a mail template.

        Returns False if template
        does not exist.
        """

        try:
            return self.env.ref(xmlid)

        except Exception:

            _logger.warning(
                "Notification template not found: %s",
                xmlid,
            )

            return False

    # =========================================================
    # Recipient Resolution
    # =========================================================

    @api.model
    def get_recipient(self, record):
        """
        Resolves recipient email.

        Priority

        account.user

        record.create_uid

        current user
        """

        if hasattr(record, "account_id"):

            account = record.account_id

            if account:

                if hasattr(account, "user_id"):

                    if account.user_id.email:

                        return account.user_id.email

        if record.create_uid:

            if record.create_uid.email:

                return record.create_uid.email

        return self.env.user.email

    # =========================================================
    # Email Sender
    # =========================================================

    @api.model
    def send_email(
        self,
        template_xmlid,
        record,
        email_to=None,
        force_send=True,
    ):
        """
        Sends an email using a template.
        """

        template = self.get_template(
            template_xmlid
        )

        if not template:

            return False

        destination = (
            email_to
            or
            self.get_recipient(record)
        )

        values = {

            "email_to": destination,

        }

        template.send_mail(

            record.id,

            force_send=force_send,

            email_values=values,

        )

        _logger.info(

            "Notification sent (%s) -> %s",

            template_xmlid,

            destination,

        )

        return True

    # =========================================================
    # Raw Email
    # =========================================================

    @api.model
    def send_message(
        self,
        subject,
        body,
        email_to,
        email_from=None,
        force_send=True,
    ):
        """
        Sends a plain email.
        """

        values = {

            "subject": subject,

            "body_html": body,

            "email_to": email_to,

            "email_from":
                email_from
                or
                self.env.user.email_formatted,

        }

        mail = self.env[
            "mail.mail"
        ].create(values)

        if force_send:

            mail.send()

        return mail

    # =========================================================
    # Template Renderer
    # =========================================================

    @api.model
    def render(
        self,
        template_xmlid,
        record,
    ):
        """
        Renders a template.

        Useful for previews.
        """

        template = self.get_template(
            template_xmlid
        )

        if not template:

            return False

        return template._render_field(

            "body_html",

            [record.id],

        )[record.id]

    # =========================================================
    # Generic Notification
    # =========================================================

    @api.model
    def notify(
        self,
        template_xmlid,
        record,
        email_to=None,
    ):
        """
        Generic notification entrypoint.
        """

        return self.send_email(

            template_xmlid,

            record,

            email_to=email_to,

        )

    # =========================================================
    # Future Channels
    # =========================================================

    @api.model
    def notify_whatsapp(
        self,
        *args,
        **kwargs,
    ):
        """
        Future implementation.
        """
        _logger.info(
            "WhatsApp notification not implemented."
        )
        return False

    @api.model
    def notify_telegram(
        self,
        *args,
        **kwargs,
    ):
        """
        Future implementation.
        """
        _logger.info(
            "Telegram notification not implemented."
        )
        return False

    @api.model
    def notify_slack(
        self,
        *args,
        **kwargs,
    ):
        """
        Future implementation.
        """
        _logger.info(
            "Slack notification not implemented."
        )
        return False

    @api.model
    def notify_teams(
        self,
        *args,
        **kwargs,
    ):
        """
        Future implementation.
        """
        _logger.info(
            "Microsoft Teams notification not implemented."
        )
        return False

    # =========================================================
    # Job Notifications
    # =========================================================

    @api.model
    def notify_job_failed(self, job):
        """
        Job execution failed.
        """

        return self.notify(
            "sce_base.mail_template_sce_job_failed",
            job,
        )

    @api.model
    def notify_job_success(self, job):
        """
        Reserved for future versions.
        """
        _logger.info(
            "Job %s finished successfully.",
            job.display_name,
        )
        return True

    # =========================================================
    # Queue Notifications
    # =========================================================

    @api.model
    def notify_queue_failed(self, queue):
        """
        Queue execution failed.

        Currently uses the Job template until
        a dedicated Queue template exists.
        """

        return self.notify(
            "sce_base.mail_template_sce_job_failed",
            queue.job_id or queue,
        )

    @api.model
    def notify_queue_success(self, queue):
        """
        Reserved for future versions.
        """

        _logger.info(
            "Queue %s processed successfully.",
            queue.display_name,
        )

        return True

    # =========================================================
    # Webhook Notifications
    # =========================================================

    @api.model
    def notify_webhook_failed(self, webhook):
        """
        Webhook processing failed.
        """

        return self.notify(
            "sce_base.mail_template_sce_system_alert",
            webhook,
        )

    @api.model
    def notify_webhook_processed(self, webhook):
        """
        Future implementation.
        """

        _logger.info(
            "Webhook %s processed.",
            webhook.display_name,
        )

        return True

    # =========================================================
    # OAuth Notifications
    # =========================================================

    @api.model
    def notify_oauth_expired(self, account):
        """
        OAuth token expired.
        """

        return self.notify(
            "sce_base.mail_template_sce_account_expired",
            account,
        )

    @api.model
    def notify_oauth_expiring(self, account):
        """
        Future implementation.
        """

        _logger.info(
            "OAuth token expiring for %s",
            account.display_name,
        )

        return True

    # =========================================================
    # Connector Notifications
    # =========================================================

    @api.model
    def notify_connector_error(self, log):
        """
        Connector execution error.
        """

        return self.notify(
            "sce_base.mail_template_sce_connector_error",
            log,
        )

    # =========================================================
    # System Notifications
    # =========================================================

    @api.model
    def notify_system_alert(self, log):
        """
        Critical system event.
        """

        return self.notify(
            "sce_base.mail_template_sce_system_alert",
            log,
        )

    # =========================================================
    # Generic Log Notifications
    # =========================================================

    @api.model
    def notify_log(self, log):
        """
        Sends notification according to log level.
        """

        if log.level == "critical":

            return self.notify_system_alert(
                log
            )

        if log.level == "error":

            return self.notify_connector_error(
                log
            )

        return True

    # =========================================================
    # Exception Notification
    # =========================================================

    @api.model
    def notify_exception(
        self,
        exception,
        record=None,
    ):
        """
        Creates a log entry and
        notifies administrators.
        """

        log = self.env[
            "sce.log"
        ].log_exception(
            exception,
        )

        return self.notify_system_alert(
            log
        )

    # =========================================================
    # Batch Notifications
    # =========================================================

    @api.model
    def notify_many(
        self,
        template_xmlid,
        records,
    ):
        """
        Sends the same notification
        to multiple records.
        """

        total = 0

        for record in records:

            if self.notify(
                template_xmlid,
                record,
            ):

                total += 1

        return total

    # =========================================================
    # Notification Dispatcher
    # =========================================================

    @api.model
    def dispatch(
        self,
        notification_type,
        record,
    ):
        """
        Generic dispatcher.
        """

        mapping = {

            "job_failed":
                self.notify_job_failed,

            "queue_failed":
                self.notify_queue_failed,

            "oauth_expired":
                self.notify_oauth_expired,

            "connector_error":
                self.notify_connector_error,

            "system_alert":
                self.notify_system_alert,

            "webhook_failed":
                self.notify_webhook_failed,

        }

        handler = mapping.get(
            notification_type
        )

        if not handler:

            _logger.warning(

                "Unknown notification type: %s",

                notification_type,

            )

            return False

        return handler(
            record
        )